language: java
jdk:
  - oraclejdk8
  
before_install:
  - cd Verification
  - chmod +x gradlew

cache:
  directories:
    - $HOME/.gradle/wrapper
    - $HOME/.gradle/caches/modules-2/files-2.1

script:
  - .gradlew check --info
  - .gradlew build --info
